apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: 033254313603.dkr.ecr.ap-southeast-1.amazonaws.com/crawler-app
            name: crawler
            env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASS
              value: 200lab
          